version: '3'

services:

  # Nginx
  nginx:
      image: nginx:1.13.12
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./config-files/nginx/conf.d:/etc/nginx/conf.d
        - ./config-files/logs/nginx/:/var/log/nginx
        - /Volumes/zithan4card/z4code:/usr/share/nginx/html
      links:
        - "php7"

  # PHP
  php7:
      build:
        context: ./build/php7
      ports:
        - "9000"
      volumes:
        - ./config-files/php/php-fpm.conf:/usr/local/php/etc/php-fpm.conf
        - ./config-files/php/php-fpm.d/www.conf:/usr/local/php/etc/php-fpm.d/www.conf
        - ./config-files/php/php.ini:/usr/local/etc/php/php.ini
        - ./config-files/logs/php/php-fpm.log:/usr/local/php/var/log/php-fpm.log
        - /Volumes/zithan4card/z4code:/usr/share/nginx/html
      links:
        - "redis"

  # Redis
  redis:
      image: redis:3.2.11
      ports:
        - "6379:6379"
      volumes:
        - ./config-files/redis/redis.conf:/usr/local/etc/redis/redis.conf
        - ./config-files/logs/redis.log:/var/log/redis/redis.log
