version: '1'

services:

  ##################### Nginx container #######################

  nginx:
      build:
        context: ./build/nginx
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
      privileged: true
      ports:
        - "${HTTP_PORT}:80"
        - "${HTTPS_PORT}:443"
      links:
        - "php71"
      volumes:
        - /Volumes/zithan4card/z4code:/var/www
        - ./nginx/conf.d:/etc/nginx/conf.d
        - /var/log/nignx:/var/log/nginx

  ##################### PHP container ####################

  php71:
      build:
        context: ./build/php71
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
      privileged: true
      ports:
        - "9071:9000"
      links:
        - "mysql"
        - "redis"
      volumes:
        - ${GLOBAL_APP_PATH}work/wwwroot:/etc/nginx/html
        - ${GLOBAL_APP_PATH}work/components/php71/config/php.ini:/usr/local/etc/php/php.ini
        - ${GLOBAL_APP_PATH}work/components/php71/log:/var/log

  ######################## Mysql container #########################################

  mysql:
      build:
        context: ./build/mysql
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
          CHANGE_SOURCE: ${GLOBAL_CHANGE_SOURCE}
      privileged: true
      ports:
        - "${MYSQL_PORT}:3306"
      volumes:
        - ${GLOBAL_APP_PATH}work/components/mysql/data:/var/lib/mysql
        - ${GLOBAL_APP_PATH}work/components/mysql/config/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        - ${GLOBAL_APP_PATH}work/components/mysql/log/error.log:/var/log/mysql/error.log
        - ${GLOBAL_APP_PATH}work/components/mysql/backup:/var/backup
        - ${GLOBAL_APP_PATH}work/components/mysql/crontabs:/var/spool/cron/crontabs
        - ${GLOBAL_APP_PATH}work/components/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  ### Redis container #########################################

  redis:
      build:
        context: ./build/redis
        args:
          TIME_ZONE: ${GLOBAL_TIME_ZONE}
      privileged: true
      ports:
        - "${REDIS_PORT}:6379"
      volumes:
        - ${GLOBAL_APP_PATH}work/components/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
        - ${GLOBAL_APP_PATH}work/components/redis/log/redis.log:/var/log/redis/redis.log
