version: '1'

services:

  # Nginx
  nginx:
      image: nginx:1.13.12
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /Volumes/zithan4card/z4code:/usr/share/nginx/html
        - /Volumes/zithan4card/z4nginx/xjw/conf.d:/etc/nginx/conf.d
        - /var/log/nignx:/var/log/nginx
      links:
        - "php7"

  # PHP
  php7:
      build:
        context: ./build/php7
      ports:
        - "9000"
      links:
        - "redis"
      volumes:
        - /Volumes/zithan4card/z4code:/usr/share/nginx/html

  # Redis
  redis:
      image: redis:3.2.11
      ports:
        - "6379:6379"
      volumes:
        - /Volumes/zithan4card/z4redis/xjw/config/redis.conf:/usr/local/etc/redis/redis.conf
        - /var/log/redis/redis.log:/var/log/redis/redis.log
